name: Sync Labels

on:
  push:
    branches: [main]
    paths:
      - '.github/labels.yml'
      - '.github/workflows/labels.yml'

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: .github/labels.yml
          dry-run: false
